package frc.robot.subsystems;

import static edu.wpi.first.units.Units.Volts;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructPublisher;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.lib.BLine.FlippingUtil;
import frc.robot.lib.BLine.FollowPath;
import frc.robot.lib.BLine.Path;
import java.util.Optional;
import java.util.Set;
import java.util.function.BooleanSupplier;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain
    extends TunerSwerveDrivetrain
    implements Subsystem {

    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation =
        Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation =
        Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;
    private Pose2d targetPoseBline = new Pose2d();
    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization =
        new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.ApplyRobotSpeeds autoRequest =
        new SwerveRequest.ApplyRobotSpeeds();

    private final PIDController pidControllerT = new PIDController(2.3, 0, 0);
    private final PIDController pidControllerR = new PIDController(3, 0, 0);
    private final PIDController pidControllerCT = new PIDController(2, 0, 0);
    private POSITIONS positionState = POSITIONS.BLUE_TOP;
    public States driveBaseState = States.Idle;
    private double xError, yError;

    StructPublisher<Pose2d> targetPosedPublisher =
        NetworkTableInstance.getDefault()
            .getStructTopic("Pid Target Pose", Pose2d.struct)
            .publish();
    StructPublisher<Pose2d> targetPosedPublisherBlineHub =
        NetworkTableInstance.getDefault()
            .getStructTopic("Pid Target Pose (BLine HUB)", Pose2d.struct)
            .publish();
    StructPublisher<Pose2d> targetPosedPublisherBlineTrench =
        NetworkTableInstance.getDefault()
            .getStructTopic("Pid Target Pose (BLine Trench)", Pose2d.struct)
            .publish();

    public enum States {
        Idle,
        Driven,
        Autonomous,
        MovingToShoot,
        InShootingPosition,
        Feeding,
        Trench,
        X,
    }

    public enum POSITIONS {
        BLUE_TOP,
        BLUE_BOTTOM,
        NEUTRAL_BLUE_TOP,
        NEUTRAL_BLUE_BOTTOM,
        NEUTRAL_RED_TOP,
        NEUTRAL_RED_BOTTOM,
        RED_TOP,
        RED_BOTTOM,
    }

    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null, // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state ->
                SignalLogger.writeString(
                    "SysIdTranslation_State",
                    state.toString()
                )
        ),
        new SysIdRoutine.Mechanism(
            output ->
                setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        pidControllerR.setTolerance(0.75);
        pidControllerT.setTolerance(0.75);
        pidControllerCT.setTolerance(0.75);
    }

    // PID to the Point (START)
    public Command BlineToHub(
        double distanceFromHub,
        double xTol,
        double yTol
    ) {
        FollowPath.Builder pathBuilder = new FollowPath.Builder(
            this,
            () -> this.getState().Pose,
            () -> this.getState().Speeds,
            speeds -> this.setControl(autoRequest.withSpeeds(speeds)),
            pidControllerT,
            pidControllerR,
            pidControllerCT
        );

        return Commands.defer(
            () -> {
                Pose2d localHub = isAllianceRed().getAsBoolean()
                    ? FlippingUtil.flipFieldPose(Constants.blueHubPose)
                    : Constants.blueHubPose;

                // Vector from hub to robot
                double dx = this.getState().Pose.getX() - localHub.getX();
                double dy = this.getState().Pose.getY() - localHub.getY();

                // Normalize and scale by desired distance
                double magnitude = Math.sqrt(dx * dx + dy * dy);
                double targetX =
                    localHub.getX() + (dx / magnitude) * distanceFromHub;
                double targetY =
                    localHub.getY() + (dy / magnitude) * distanceFromHub;

                // Face the hub from the target point
                double angleToHub = Math.atan2(
                    localHub.getY() - targetY,
                    localHub.getX() - targetX
                );

                Pose2d localPose = new Pose2d(
                    targetX,
                    targetY,
                    new Rotation2d(angleToHub)
                );

                targetPosedPublisherBlineHub.accept(localPose);
                targetPoseBline = localPose;

                double[] errors = getBlineErrors(localPose);
                xError = errors[0];
                yError = errors[1];

                if (Math.abs(yError) < yTol && Math.abs(xError) < xTol) {
                    Path path = new Path(
                        new Path.Waypoint(this.getState().Pose),
                        new Path.Waypoint(localPose)
                    );
                    driveBaseState = States.MovingToShoot;
                    return pathBuilder.build(path);
                } else {
                    driveBaseState = States.InShootingPosition;
                    return Commands.none();

                }
            },
            Set.of(this)
        );
    }

    private Command BlineToAllianceTrench(
        Pose2d targetPose,
        Boolean isAllianceRed,
        Boolean goingOut
    ) {
        FollowPath.Builder pathBuilder = new FollowPath.Builder(
            this,
            () -> this.getState().Pose,
            () -> this.getState().Speeds,
            speeds -> this.setControl(autoRequest.withSpeeds(speeds)),
            pidControllerT,
            pidControllerR,
            pidControllerCT
        );

        return Commands.defer(() -> {

            Pose2d trenchWaypoint = new Pose2d(targetPose.getX() - 3, targetPose.getY(), new Rotation2d(0));
            Pose2d localPose = targetPose;
            targetPoseBline = localPose;
            if (!goingOut) {
                localPose = new Pose2d(localPose.getX() - 3, localPose.getY(),
                        localPose.getRotation().plus(new Rotation2d(Math.PI)));
                trenchWaypoint = new Pose2d(localPose.getX() + 3, localPose.getY(), new Rotation2d(0));
            }

            trenchWaypoint = isAllianceRed ? FlippingUtil.flipFieldPose(trenchWaypoint) : trenchWaypoint;
            localPose = isAllianceRed ? FlippingUtil.flipFieldPose(localPose) : localPose;

                targetPosedPublisherBlineTrench.accept(trenchWaypoint);

                double[] errors = getBlineErrors(localPose);
                xError = errors[0];
                yError = errors[1];

                Path path = new Path(
                    new Path.Waypoint(this.getState().Pose),
                    new Path.TranslationTarget(trenchWaypoint.getTranslation()),
                    new Path.Waypoint(localPose)
                );

                return pathBuilder.build(path);
            },
            Set.of(this)
        );
    }

    public Command BlineToTrench() {
        return Commands.defer(
            () -> {
                switch (positionState) {
                    case BLUE_TOP:
                        return BlineToAllianceTrench(
                            Constants.targetPoseTrenchLeft,
                            false,
                            true
                        );
                    case BLUE_BOTTOM:
                        return BlineToAllianceTrench(
                            Constants.targetPoseTrenchRight,
                            false,
                            true
                        );
                    case NEUTRAL_BLUE_TOP:
                        return BlineToAllianceTrench(
                            Constants.targetPoseTrenchLeft,
                            false,
                            false
                        );
                    case NEUTRAL_BLUE_BOTTOM:
                        return BlineToAllianceTrench(
                            Constants.targetPoseTrenchRight,
                            false,
                            false
                        );
                    case NEUTRAL_RED_TOP:
                        return BlineToAllianceTrench(
                            Constants.targetPoseTrenchLeft,
                            true,
                            false
                        );
                    case NEUTRAL_RED_BOTTOM:
                        return BlineToAllianceTrench(
                            Constants.targetPoseTrenchRight,
                            true,
                            false
                        );
                    case RED_TOP:
                        return BlineToAllianceTrench(
                            Constants.targetPoseTrenchLeft,
                            true,
                            true
                        );
                    case RED_BOTTOM:
                        return BlineToAllianceTrench(
                            Constants.targetPoseTrenchRight,
                            true,
                            true
                        );
                    default:
                        return Commands.none();
                }
            },
            Set.of(this)
        );
    }

    public BooleanSupplier isRobotInShootingZone(){

            if (isAllianceRed().getAsBoolean()){
                return () -> positionState == POSITIONS.RED_TOP || positionState == POSITIONS.RED_BOTTOM;
            } else {
                return () -> positionState == POSITIONS.BLUE_TOP || positionState == POSITIONS.BLUE_BOTTOM;
            }
        
    }
    public double[] getBlineErrors(Pose2d targetPose) {
        double _xError = targetPose.getX() - this.getState().Pose.getX();
        double _yError = targetPose.getY() - this.getState().Pose.getY();
        return new double[] { _xError, _yError };
    }

    // PID To Point (END)

    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(
            drivetrainConstants,
            odometryUpdateFrequency,
            odometryStandardDeviation,
            visionStandardDeviation,
            modules
        );
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {

        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance()
                .ifPresent(allianceColor -> {
                    setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red
                            ? kRedAlliancePerspectiveRotation
                            : kBlueAlliancePerspectiveRotation
                    );
                    m_hasAppliedOperatorPerspective = true;
                });
        }
        double robotX = this.getState().Pose.getX();
        double robotY = this.getState().Pose.getY();

        double fieldQuarterX = Constants.FIELD_LENGTH / 4;
        double fieldHalfX = Constants.FIELD_LENGTH / 2;
        double fieldThreeQuarterX = (3 * Constants.FIELD_LENGTH) / 4;
        double fieldCenterY = Constants.FIELD_WIDTH / 2;

        if (robotX < fieldQuarterX && robotY > fieldCenterY) {
            positionState = POSITIONS.BLUE_TOP;
        } else if (robotX < fieldQuarterX && robotY <= fieldCenterY) {
            positionState = POSITIONS.BLUE_BOTTOM;
        } else if (
            robotX >= fieldQuarterX &&
            robotX < fieldHalfX &&
            robotY > fieldCenterY
        ) {
            positionState = POSITIONS.NEUTRAL_BLUE_TOP;
        } else if (
            robotX >= fieldQuarterX &&
            robotX < fieldHalfX &&
            robotY <= fieldCenterY
        ) {
            positionState = POSITIONS.NEUTRAL_BLUE_BOTTOM;
        } else if (
            robotX >= fieldHalfX &&
            robotX < fieldThreeQuarterX &&
            robotY > fieldCenterY
        ) {
            positionState = POSITIONS.NEUTRAL_RED_BOTTOM;
        } else if (
            robotX >= fieldHalfX &&
            robotX < fieldThreeQuarterX &&
            robotY <= fieldCenterY
        ) {
            positionState = POSITIONS.NEUTRAL_RED_TOP;
        } else if (robotX >= fieldThreeQuarterX && robotY > fieldCenterY) {
            positionState = POSITIONS.RED_BOTTOM;
        } else {
            positionState = POSITIONS.RED_TOP;
        }
        Path.setDefaultGlobalConstraints(new Path.DefaultGlobalConstraints(
                5.0, // max velocity m/s
                10.0, // max acceleration m/s²
                360.0, // max angular velocity deg/s
                360.0, // max angular acceleration deg/s²
                0.2, // end translation tolerance meters
                2.0, // end rotation tolerance degrees
                0.5 // intermediate handoff radius meters
        ));
        SmartDashboard.putString("Robot State", positionState.toString());
        SmartDashboard.putNumber("Robot x", robotX);
        SmartDashboard.putNumber("Robot y", robotY);
        SmartDashboard.putNumber("xError", targetPoseBline.getX() - robotX);
        SmartDashboard.putNumber("yError", targetPoseBline.getY() - robotY);
        SmartDashboard.putNumber(
            "rError",
            targetPoseBline.getRotation().getRadians() -
            getRobotRotation().getAsDouble()
        );
        SmartDashboard.putBoolean(
            "Robot Side",
            isRobotLeftHub().getAsBoolean()
        );
        SmartDashboard.putBoolean(
            "Bline Available",
            Math.abs(targetPoseBline.getY() - this.getState().Pose.getY()) <
                2.40 &&
            Math.abs(targetPoseBline.getX() - this.getState().Pose.getX()) <
            1.90
        );
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    @Override
    public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters,
            double timestampSeconds,
            Matrix<N3, N1> visionMeasurementStdDevs) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds),
                visionMeasurementStdDevs);
    }

    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public DoubleSupplier getRobotX() {
        return () -> this.getState().Pose.getX();
    }

    public DoubleSupplier getRobotY() {
        return () -> this.getState().Pose.getY();
    }

    public DoubleSupplier getRobotRotation() {
        return () -> this.getState().Pose.getRotation().getRadians();
    }

    public BooleanSupplier isRobotLeftHub() {
        return () ->
            (this.getState().Pose.getX() < Constants.blueHubPose.getX() &&
                this.getState().Pose.getY() > Constants.blueHubPose.getY()) ||
            (this.getState().Pose.getX() > Constants.redHubPose.getX() &&
                this.getState().Pose.getY() < Constants.redHubPose.getY());
    }

    public BooleanSupplier isAllianceRed() {
        return () ->
            DriverStation.getAlliance()
                .orElse(Alliance.Blue)
                .equals(Alliance.Red);
    }
}
