package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.function.BooleanSupplier;
import java.util.function.IntSupplier;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.swerve.jni.SwerveJNI.DriveState;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.path.GoalEndState;
import com.pathplanner.lib.path.PathConstraints;
import com.pathplanner.lib.path.PathPlannerPath;
import com.pathplanner.lib.path.Waypoint;

import frc.robot.lib.BLine.FollowPath;
import frc.robot.lib.BLine.Path;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.ProfiledPIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.trajectory.TrapezoidProfile;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructPublisher;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import frc.robot.Constants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import edu.wpi.first.math.controller.PIDController;
import java.util.function.DoubleSupplier;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;
    private double kpx = 5, kix = 0, kdx = 0;
    private double kpy = 1.5, kiy = 0, kdy = 0;
    private double kpr = 5, kir = 0, kdr = 0;
    private Pose2d targetPoseBlineHub = new Pose2d();
    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();
    private final SwerveRequest.ApplyRobotSpeeds autoRequest = new SwerveRequest.ApplyRobotSpeeds();

    private final ProfiledPIDController pidControllerProfiledX = new ProfiledPIDController(kpx, kix, kdx,
            new TrapezoidProfile.Constraints(Constants.MaxDrivingSpeed, 10));
    private final ProfiledPIDController pidControllerProfiledY = new ProfiledPIDController(kpy, kiy, kdy,
            new TrapezoidProfile.Constraints(Constants.MaxDrivingSpeed, 10));
    private final ProfiledPIDController pidControllerProfiledR = new ProfiledPIDController(kpr, kir, kdr,
            new TrapezoidProfile.Constraints(Constants.MaxAngularDrivingSpeed, 5));

    private final PIDController pidControllerT = new PIDController(2.3, 0, 0.2);
    private final PIDController pidControllerR = new PIDController(4, 0, 0);
    private final PIDController pidControllerCT = new PIDController(2, 0, 0);
    private static int isRed;

    StructPublisher<Pose2d> targetPosedPublisher = NetworkTableInstance.getDefault()
            .getStructTopic("Pid Target Pose", Pose2d.struct).publish();
    StructPublisher<Pose2d> targetPosedPublisherBline = NetworkTableInstance.getDefault()
            .getStructTopic("Pid Target Pose (BLine)", Pose2d.struct).publish();

    private static RobotConfig config;
    static {
        try {
            config = RobotConfig.fromGUISettings();
        } catch (Exception e) {
            // Handle exception as needed
            e.printStackTrace();
        }
    }

    /*
     * SysId routine for characterizing translation. This is used to find PID gains
     * for the drive motors.
     */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> setControl(m_translationCharacterization.withVolts(output)),
                    null,
                    this));
    /**
     * /* SysId routine for characterizing steer. This is used to find PID gains for
     * the steer motors.
     */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(7), // Use dynamic voltage of 7 V
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    volts -> setControl(m_steerCharacterization.withVolts(volts)),
                    null,
                    this));

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle
     * HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
     * importing the log to SysId.
     */

    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    /* This is in radians per second², but SysId only supports "volts per second" */
                    Volts.of(Math.PI / 6).per(Second),
                    /* This is in radians per second, but SysId only supports "volts" */
                    Volts.of(Math.PI),
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> {
                        /* output is actually radians per second, but SysId only supports "volts" */
                        setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                        /* also log the requested output for SysId */
                        SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
                    },
                    null,
                    this));

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param modules             Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        AutoBuilder.configure(() -> this.getState().Pose, this::resetPose,
                () -> this.getState().Speeds,
                (speeds, feedForwards) -> this.setControl(autoRequest.withSpeeds(speeds)),
                new PPHolonomicDriveController(new PIDConstants(0, 0, 0), new PIDConstants(0, 0, 0)),
                config,
                () -> {
                    var alliance = DriverStation.getAlliance();
                    if (alliance.isPresent()) {
                        return alliance.get() == DriverStation.Alliance.Red;
                    }
                    return false;
                },
                this);
        SmartDashboard.putNumber("drive/kpx", kpx);
        SmartDashboard.putNumber("drive/kix", kix);
        SmartDashboard.putNumber("drive/kdx", kdx);
        SmartDashboard.putNumber("drive/kpy", kpy);
        SmartDashboard.putNumber("drive/kiy", kiy);
        SmartDashboard.putNumber("drive/kdy", kdy);
        SmartDashboard.putNumber("drive/kpr", kpr);
        SmartDashboard.putNumber("drive/kir", kir);
        SmartDashboard.putNumber("drive/kdr", kdr);
    }

    private PathPlannerPath path;

    private BooleanSupplier pidReachedSetpointAngle = () -> {
        boolean reachedSetpoint = (pidControllerProfiledR.atSetpoint());
        return reachedSetpoint;
    };

    // PID to the Point (START)

    public Command BlineToPoint(Pose2d targetPose, BooleanSupplier isRedBoolean) {
        targetPoseBlineHub = targetPose;
        pidControllerR.setTolerance(0.75);
        pidControllerT.setTolerance(0.75);
        pidControllerCT.setTolerance(0.75);
        Path.setDefaultGlobalConstraints(new Path.DefaultGlobalConstraints(
                5.0, // max velocity m/s
                6.0, // max acceleration m/s²
                360.0, // max angular velocity deg/s
                360.0, // max angular acceleration deg/s²
                0.05, // end translation tolerance meters
                2.0, // end rotation tolerance degrees
                0.3 // intermediate handoff radius meters
        ));
        FollowPath.Builder pathBuilder = new FollowPath.Builder(
                this,
                () -> this.getState().Pose,
                () -> this.getState().Speeds,
                (speeds) -> this.setControl(autoRequest.withSpeeds(speeds)),
                pidControllerT, pidControllerR, pidControllerCT);
        // Pose2d localPose = isRedBoolean.getAsBoolean() ?
        // FlippingUtil.flipFieldPose(targetPose) : targetPose;
        targetPosedPublisherBline.accept(targetPose);
        return Commands.defer(() -> {
            Path path = new Path(
                    new Path.Waypoint(this.getState().Pose),
                    new Path.Waypoint(targetPose));

            return pathBuilder.build(path);
        }, Set.of(this));
    }

    private BooleanSupplier pidReachedGoal = () -> {
        boolean reachedGoal = (pidControllerProfiledX.atGoal() && pidControllerProfiledY.atGoal()
                && pidControllerProfiledR.atGoal());
        SmartDashboard.putBoolean("xAtSetpoint", pidControllerProfiledX.atSetpoint());
        SmartDashboard.putBoolean("yAtSetpoint", pidControllerProfiledY.atSetpoint());
        SmartDashboard.putBoolean("rAtSetpoint", pidControllerProfiledR.atSetpoint());
        SmartDashboard.putNumber("xSetpoint", pidControllerProfiledX.getSetpoint().position);
        SmartDashboard.putNumber("ySetpoint", pidControllerProfiledY.getSetpoint().position);
        SmartDashboard.putNumber("rSetpoint", pidControllerProfiledR.getSetpoint().position);

        return reachedGoal;
    };

    private Command imPiddingIt(BooleanSupplier isRedBoolean) {
        return new InstantCommand(() -> {
            isRed = isRedBoolean.getAsBoolean() ? -1 : 1;
            System.out.println(isRed);
            ChassisSpeeds fieldCentricRobotSpeeds = ChassisSpeeds.fromRobotRelativeSpeeds(this.getState().Speeds,
                    this.getState().RawHeading);
            double vxFieldCentric = fieldCentricRobotSpeeds.vxMetersPerSecond;
            double vyFieldCentric = fieldCentricRobotSpeeds.vyMetersPerSecond;

            SmartDashboard.putNumber("vx", vxFieldCentric);
            SmartDashboard.putNumber("vy", vyFieldCentric);

            pidControllerProfiledX.reset(this.getState().Pose.getX(), vxFieldCentric);
            pidControllerProfiledY.reset(this.getState().Pose.getY(), vyFieldCentric);
            pidControllerProfiledR.reset(this.getState().RawHeading.getRadians());
        }).andThen(this.applyRequest(() -> new SwerveRequest.FieldCentric()
                .withVelocityX(pidControllerProfiledX.calculate(this.getState().Pose.getX()) * isRed)
                .withVelocityY(pidControllerProfiledY.calculate(this.getState().Pose.getY()) * isRed)
                .withRotationalRate(pidControllerProfiledR.calculate(this.getState().RawHeading.getRadians())))
                .until(pidReachedGoal));
    }

    public Command pidToPoint(Pose2d targetPose, BooleanSupplier isRedBoolean) {
        // targetPose.rotateAround();
        pidControllerProfiledR.enableContinuousInput(-Math.PI, Math.PI);

        pidControllerProfiledX.setTolerance(0.05);
        pidControllerProfiledY.setTolerance(0.05);
        pidControllerProfiledR.setTolerance(0.0174532925);
        // pidControllerX.

        pidControllerProfiledX.setGoal(targetPose.getX());
        pidControllerProfiledY.setGoal(targetPose.getY());
        pidControllerProfiledR.setGoal(targetPose.getRotation().getRadians());

        targetPosedPublisher.accept(targetPose);
        return Commands.defer(() -> imPiddingIt(isRedBoolean), Set.of(this));
    }

    // PID To Point (END)

    private Command imPiddingItRotation(Supplier<Double> controller1Y, Supplier<Double> controller1X) {
        return this.applyRequest(() -> new SwerveRequest.FieldCentric()
                .withVelocityX(-Math.pow(controller1X.get(), 3) * Constants.MaxDrivingSpeed)
                .withVelocityY(-Math.pow(controller1Y.get(), 3) * Constants.MaxDrivingSpeed)
                .withRotationalRate(pidControllerProfiledR.calculate(this.getState().RawHeading.getRadians())))
                .until(pidReachedSetpointAngle);
    }

    public Command pidToRotation(double newRotation, Supplier<Double> controller1Y, Supplier<Double> controller1X) {
        pidControllerProfiledR.enableContinuousInput(-Math.PI, Math.PI);

        pidControllerProfiledR.setGoal(newRotation);

        return Commands.defer(() -> imPiddingItRotation(controller1Y, controller1X), Set.of(this));
    }

    private Command getPathPlannerPath(Pose2d targetPose) {
        Pose2d currentPose = this.getState().Pose;

        ChassisSpeeds robotRobotRelativeVelocities = this.getState().Speeds;
        ChassisSpeeds robotFieldRelativeVelocities = ChassisSpeeds.fromRobotRelativeSpeeds(robotRobotRelativeVelocities,
                this.getState().RawHeading);

        currentPose = new Pose2d(currentPose.getX(), currentPose.getY(), new Rotation2d(
                robotFieldRelativeVelocities.vxMetersPerSecond, robotFieldRelativeVelocities.vyMetersPerSecond));
        targetPose = new Pose2d(targetPose.getX(), targetPose.getY(), new Rotation2d(
                Math.atan2(targetPose.getX() - currentPose.getX(), targetPose.getY() - currentPose.getY())));

        List<Waypoint> waypoints = PathPlannerPath.waypointsFromPoses(
                currentPose,
                targetPose);

        path = new PathPlannerPath(
                waypoints,
                new PathConstraints(3.0, 3.0, 2 * Math.PI, 4 * Math.PI),
                null,
                new GoalEndState(0.0, targetPose.getRotation()));

        path.preventFlipping = true;
        System.out.println("Pooey");
        return AutoBuilder.followPath(path);
    }

    public Command driveToPose(Pose2d targetPose) {
        return Commands.defer(() -> getPathPlannerPath(targetPose), Set.of(this));
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve
     *                                  drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz
     *                                  on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation,
                modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve
     * drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {

        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply
         * it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts
         * mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is
         * disabled.
         * This ensures driving behavior doesn't change until an explicit disable event
         * occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red
                                ? kRedAlliancePerspectiveRotation
                                : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
            });
        }
        SmartDashboard.getNumber("drive/kpx", kpx);
        SmartDashboard.getNumber("drive/kix", kix);
        SmartDashboard.getNumber("drive/kdx", kdx);
        SmartDashboard.getNumber("drive/kpy", kpy);
        SmartDashboard.getNumber("drive/kiy", kiy);
        SmartDashboard.getNumber("drive/kdy", kdy);
        SmartDashboard.getNumber("drive/kpr", kpr);
        SmartDashboard.getNumber("drive/kir", kir);
        SmartDashboard.getNumber("drive/kdr", kdr);
        SmartDashboard.putNumber("ErrorX", targetPoseBlineHub.getX() - getRobotX().getAsDouble());
        SmartDashboard.putNumber("ErrorY", targetPoseBlineHub.getY() - getRobotY().getAsDouble());
        SmartDashboard.putNumber("ErrorR",
                targetPoseBlineHub.getRotation().getRadians() - getRobotRotation().getAsDouble());
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision
     *                              camera.
     * @param timestampSeconds      The timestamp of the vision measurement in
     *                              seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters    The pose of the robot as measured by the
     *                                 vision camera.
     * @param timestampSeconds         The timestamp of the vision measurement in
     *                                 seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose
     *                                 measurement
     *                                 in the form [x, y, theta]ᵀ, with units in
     *                                 meters and radians.
     */
    @Override
    public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters,
            double timestampSeconds,
            Matrix<N3, N1> visionMeasurementStdDevs) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds),
                visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is
     *         empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public DoubleSupplier getRobotX() {
        return () -> this.getState().Pose.getX();
    }

    public DoubleSupplier getRobotY() {
        return () -> this.getState().Pose.getY();
    }

    public DoubleSupplier getRobotRotation() {
        return () -> this.getState().Pose.getRotation().getRadians();
    }

}
