package frc.robot.subsystems;

import static edu.wpi.first.units.Units.Volts;

import java.util.Optional;
import java.util.Set;
import java.util.function.BooleanSupplier;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructPublisher;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.lib.BLine.FlippingUtil;
import frc.robot.lib.BLine.FollowPath;
import frc.robot.lib.BLine.Path;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;
    private Pose2d targetPoseBline = new Pose2d();
    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.ApplyRobotSpeeds autoRequest = new SwerveRequest.ApplyRobotSpeeds();

    private final PIDController pidControllerT = new PIDController(2.3, 0, 0.2);
    private final PIDController pidControllerR = new PIDController(4, 0, 0);
    private final PIDController pidControllerCT = new PIDController(2, 0, 0);
    private POSITIONS state = POSITIONS.BLUE_TOP;

    private double xError, yError;

    StructPublisher<Pose2d> targetPosedPublisher = NetworkTableInstance.getDefault()
            .getStructTopic("Pid Target Pose", Pose2d.struct).publish();
    StructPublisher<Pose2d> targetPosedPublisherBlineHub = NetworkTableInstance.getDefault()
            .getStructTopic("Pid Target Pose (BLine HUB)", Pose2d.struct).publish();
    StructPublisher<Pose2d> targetPosedPublisherBlineTrench = NetworkTableInstance.getDefault()
            .getStructTopic("Pid Target Pose (BLine Trench)", Pose2d.struct).publish();

    private enum States {
        Idle,
        Driven,
        Autonomous,
        MovingToShoot,
        Feeding,
        Trench,
        X
    }

    public enum POSITIONS {
        BLUE_TOP,
        BLUE_BOTTOM,
        NEUTRAL_BLUE_TOP,
        NEUTRAL_BLUE_BOTTOM,
        NEUTRAL_RED_TOP,
        NEUTRAL_RED_BOTTOM,
        RED_TOP,
        RED_BOTTOM
    }


    /*
     * SysId routine for characterizing translation. This is used to find PID gains
     * for the drive motors.
     */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> setControl(m_translationCharacterization.withVolts(output)),
                    null,
                    this));

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param modules             Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        pidControllerR.setTolerance(0.75);
        pidControllerT.setTolerance(0.75);
        pidControllerCT.setTolerance(0.75);
    }

    // PID to the Point (START)
    public Command BlineToHub(Pose2d hubPose, double distanceFromHub, double xTol, double yTol) {
        FollowPath.Builder pathBuilder = new FollowPath.Builder(
                this,
                () -> this.getState().Pose,
                () -> this.getState().Speeds,
                (speeds) -> this.setControl(autoRequest.withSpeeds(speeds)),
                pidControllerT, pidControllerR, pidControllerCT);

        return Commands.defer(() -> {
            Pose2d localHub = isAllianceRed().getAsBoolean() ? FlippingUtil.flipFieldPose(hubPose) : hubPose;

            // Vector from hub to robot
            double dx = this.getState().Pose.getX() - localHub.getX();
            double dy = this.getState().Pose.getY() - localHub.getY();

            // Normalize and scale by desired distance
            double magnitude = Math.sqrt(dx * dx + dy * dy);
            double targetX = localHub.getX() + (dx / magnitude) * distanceFromHub;
            double targetY = localHub.getY() + (dy / magnitude) * distanceFromHub;

            // Face the hub from the target point
            double angleToHub = Math.atan2(
                    localHub.getY() - targetY,
                    localHub.getX() - targetX);

            Pose2d localPose = new Pose2d(targetX, targetY, new Rotation2d(angleToHub));

            targetPosedPublisherBlineHub.accept(localPose);
            targetPoseBline = localPose;

            double[] errors = getBlineErrors(localPose);
            xError = errors[0];
            yError = errors[1];

            if (Math.abs(yError) < yTol && Math.abs(xError) < xTol) {
                Path path = new Path(
                        new Path.Waypoint(this.getState().Pose),
                        new Path.Waypoint(localPose));
                return pathBuilder.build(path);
            } else {
                return Commands.none();
            }
        }, Set.of(this));
    }

    private Command BlineToAllianceTrench(Pose2d targetPose, Boolean isAllianceRed, Boolean goingOut) {

        FollowPath.Builder pathBuilder = new FollowPath.Builder(
                this,
                () -> this.getState().Pose,
                () -> this.getState().Speeds,
                (speeds) -> this.setControl(autoRequest.withSpeeds(speeds)),
                pidControllerT, pidControllerR, pidControllerCT);

        return Commands.defer(() -> {

            Pose2d trenchWaypoint = new Pose2d(targetPose.getX() - 3, targetPose.getY(), new Rotation2d(0));
            Pose2d localPose = targetPose;
            targetPoseBline = localPose;
            if (!goingOut) {
                localPose = new Pose2d(localPose.getX() - 3, localPose.getY(),
                        localPose.getRotation().plus(new Rotation2d(Math.PI)));
                trenchWaypoint = new Pose2d(targetPose.getX() + 3, targetPose.getY(), new Rotation2d(0));
            }

            trenchWaypoint = isAllianceRed ? FlippingUtil.flipFieldPose(trenchWaypoint) : trenchWaypoint;
            localPose = isAllianceRed ? FlippingUtil.flipFieldPose(localPose) : localPose;

            targetPosedPublisherBlineTrench.accept(trenchWaypoint);

            double[] errors = getBlineErrors(localPose);
            xError = errors[0];
            yError = errors[1];

            Path path = new Path(
                    new Path.Waypoint(this.getState().Pose),
                    new Path.TranslationTarget(trenchWaypoint.getTranslation()),
                    new Path.Waypoint(localPose));

            return pathBuilder.build(path);

        }, Set.of(this));

    }

    public Command BlineToTrench() {

        return Commands.defer(() -> {
            switch (state) {
                case BLUE_TOP:
                    return BlineToAllianceTrench(Constants.targetPoseTrenchLeft, false, true);
                case BLUE_BOTTOM:
                    return BlineToAllianceTrench(Constants.targetPoseTrenchRight, false, true);
                case NEUTRAL_BLUE_TOP:
                    return BlineToAllianceTrench(Constants.targetPoseTrenchLeft, false, false);
                case NEUTRAL_BLUE_BOTTOM:
                    return BlineToAllianceTrench(Constants.targetPoseTrenchRight, false, false);
                case NEUTRAL_RED_TOP:
                    return BlineToAllianceTrench(Constants.targetPoseTrenchLeft, true, false);
                case NEUTRAL_RED_BOTTOM:
                    return BlineToAllianceTrench(Constants.targetPoseTrenchRight, true, false);
                case RED_TOP:
                    return BlineToAllianceTrench(Constants.targetPoseTrenchLeft, true, true);
                case RED_BOTTOM:
                    return BlineToAllianceTrench(Constants.targetPoseTrenchRight, true, true);
                default:
                    return Commands.none();
            }

        }, Set.of(this));
    }

    public double[] getBlineErrors(Pose2d targetPose) {
        double _xError = targetPose.getX() - this.getState().Pose.getX();
        double _yError = targetPose.getY() - this.getState().Pose.getY();
        return new double[] { _xError, _yError };
    }

    // PID To Point (END)

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve
     *                                  drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz
     *                                  on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation,
                modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve
     * drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {

        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply
         * it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts
         * mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is
         * disabled.
         * This ensures driving behavior doesn't change until an explicit disable event
         * occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red
                                ? kRedAlliancePerspectiveRotation
                                : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
            });
        }
        double robotX = this.getState().Pose.getX();
        double robotY = this.getState().Pose.getY();

        double fieldQuarterX = Constants.FIELD_LENGTH / 4;
        double fieldHalfX = Constants.FIELD_LENGTH / 2;
        double fieldThreeQuarterX = 3 * Constants.FIELD_LENGTH / 4;
        double fieldCenterY = Constants.FIELD_WIDTH / 2;

        if (robotX < fieldQuarterX && robotY > fieldCenterY) {
            state = POSITIONS.BLUE_TOP;
        } else if (robotX < fieldQuarterX && robotY <= fieldCenterY) {
            state = POSITIONS.BLUE_BOTTOM;
        } else if (robotX >= fieldQuarterX && robotX < fieldHalfX && robotY > fieldCenterY) {
            state = POSITIONS.NEUTRAL_BLUE_TOP;
        } else if (robotX >= fieldQuarterX && robotX < fieldHalfX && robotY <= fieldCenterY) {
            state = POSITIONS.NEUTRAL_BLUE_BOTTOM;
        } else if (robotX >= fieldHalfX && robotX < fieldThreeQuarterX && robotY > fieldCenterY) {
            state = POSITIONS.NEUTRAL_RED_BOTTOM;
        } else if (robotX >= fieldHalfX && robotX < fieldThreeQuarterX && robotY <= fieldCenterY) {
            state = POSITIONS.NEUTRAL_RED_TOP;
        } else if (robotX >= fieldThreeQuarterX && robotY > fieldCenterY) {
            state = POSITIONS.RED_BOTTOM;
        } else {
            state = POSITIONS.RED_TOP;
        }
        SmartDashboard.putString("Robot State", state.toString());
        SmartDashboard.putNumber("Robot x", robotX);
        SmartDashboard.putNumber("Robot y", robotY);
        SmartDashboard.putNumber("xError", targetPoseBline.getX() - robotX);
        SmartDashboard.putNumber("yError", targetPoseBline.getY() - robotY);
        SmartDashboard.putNumber("rError",
                targetPoseBline.getRotation().getRadians() - getRobotRotation().getAsDouble());
        SmartDashboard.putBoolean("Robot Side", isRobotLeftHub().getAsBoolean());
        SmartDashboard.putBoolean("Bline Available",
                Math.abs(targetPoseBline.getY() - this.getState().Pose.getY()) < 2.40
                        && Math.abs(targetPoseBline.getX() - this.getState().Pose.getX()) < 1.90);
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);

    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision
     *                              camera.
     * @param timestampSeconds      The timestamp of the vision measurement in
     *                              seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters    The pose of the robot as measured by the
     *                                 vision camera.
     * @param timestampSeconds         The timestamp of the vision measurement in
     *                                 seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose
     *                                 measurement
     *                                 in the form [x, y, theta]ᵀ, with units in
     *                                 meters and radians.
     */
    @Override
    public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters,
            double timestampSeconds,
            Matrix<N3, N1> visionMeasurementStdDevs) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds),
                visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is
     *         empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public DoubleSupplier getRobotX() {
        return () -> this.getState().Pose.getX();
    }

    public DoubleSupplier getRobotY() {
        return () -> this.getState().Pose.getY();
    }

    public DoubleSupplier getRobotRotation() {
        return () -> this.getState().Pose.getRotation().getRadians();
    }

    public BooleanSupplier isRobotLeftHub() {
        return () -> (this.getState().Pose.getX() < Constants.blueHubPose.getX()
                && this.getState().Pose.getY() > Constants.blueHubPose.getY())
                || (this.getState().Pose.getX() > Constants.redHubPose.getX()
                        && this.getState().Pose.getY() < Constants.redHubPose.getY());
    }

    public BooleanSupplier isAllianceRed() {
        return () -> DriverStation.getAlliance().orElse(Alliance.Blue)
                .equals(Alliance.Red);
    }

}
